image: docker:latest
services:
- docker:dind

stages:
- build

variables:
  RELEASE_IMAGE: $CI_REGISTRY/parrotlync/frooty/frooty:latest

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  
build:
  stage: build
  script:
    - docker build -t $RELEASE_IMAGE .
    - docker push $RELEASE_IMAGE
  only:
    - master
